### ISSUE TITLE
Encrypt Output is error

### ISSUE THREAD

**Issue by Sean-Wang** [jslim89/RSA-objc#1]
![snip20150203_4](https://cloud.githubusercontent.com/assets/1193073/6020024/a499c2f4-abe1-11e4-8af4-4389001446f1.png)
![snip20150203_5](https://cloud.githubusercontent.com/assets/1193073/6020025/a5f630c4-abe1-11e4-9a9e-e655d37786c8.png)

Every time, there is other words in the end of decrypt text. But iOS native is OK. @jslim89

**Comment by jslim89** [comment]
Hmm...
Actually the decryption part got some _extra bytes_ behind.
The _extra bytes_ I believe is because the `char` don't have a `\0` behind or what, that's why in the console there sometime you can see those unknown characters after the plain text.
But then, when I try to convert to `NSString`, the _extra bytes_ just gone.
Perhaps is be cause of this problem, it cause some problem in the online generator.

Recently I'm quite busy and I have no time to figure this out. Perhaps you can folk this project and try to figure it out, and I will be happy if you can submit a pull request as well.

**Comment by zunemoe** [comment]
@Sean-Wang did you solve the problem yet? I also got the same problem. When I encrypt "Hello World!" from iOS and decrypt from Java side got the result like that "Hello World! public encrypt: %@ public encrypt hex string: %@".
Actually the extra text are from my NSLog. I don't know why and don't know how to fix.
Let me know if you have the solution. Thanks

P.S when I encrypt from Java side and decrypt from iOS side, got the correct result.

**Comment by lokielse** [comment]
+1

**Comment by transaction** [comment]
Also get added text in my encrypted NSString, coming from NSLog. Currently 'fixed' it using a custom delimiter.

There's also an issue sometimes with added data after the base64 string, for example after the ==, there's `-Gb~õπÿ¯`

Decrypting that string fails, when I remove everything after ==, it works. This happens about 20% of the time.

**Comment by jslim89** [comment]
@transaction You may submit a pull request for this fixes

**Comment by transaction** [comment]
@jslim89 I wouldn't call them fixes so it would mostly mutilate the source. It's basically a loop till the convertion to NSString doesn't give nil (it gives nil if there's added data after ==).

For the NSLog stuff after decrypting , I add a custom delimiter (say 'DE8374') after the text that needs to be encrypted. On the other side I split it using that string and take the first element in the array.

**Comment by satoshin21** [comment]
RSA-objc/RSA-objc/js_rsa.c
129L change to 

``` c
// "chunk_length" to "plain_char_len"
int result_length = RSA_public_encrypt(plain_char_len, plain_chunk, result_chunk, rsa_publicKey, RSA_PKCS1_PADDING);
```

It works to me.

**Comment by Sean-Wang** [comment]
@SatoshiN211 Please submit a pull request for this fixes, thanks.

**Comment by jslim89** [comment]
@SatoshiN211 Yes, it works, for _string length < chunk length_. If you try my example project, just change that line, and run it _(the default string is **Lorem ipsum ...**)_ and it will crash. But thanks anyway, at least now I know where the problem come from.

**Comment by jslim89** [comment]
Already fixed. See https://github.com/jslim89/RSA-objc/commit/cbcf8c0bbebff9163e8bc422c6c860306f9879cd
