### ISSUE TITLE
Randomly fails to encrypt, especially when using 2048 bit keys

### ISSUE THREAD

**Issue by renfeisong** [jslim89/RSA-objc#11]
With a 512 bit public key, public key encryption (using `js_public_encrypt` function) fails occasionally. It doesn't print any error messages in case of a failure and just returns a broken string. When using a 2048 bit public key, the failure rate increases significantly (almost every time, but my data set (some JSON strings) might not be representative.). However when it fails to encrypt, a second or third re-attempt with the same configuration usually works. Very strange.

**Comment by jslim89** [comment]
Hi, it actually is a known issue #3, I'm quite busy recently and may not have time to fix it. If you can fix it and submit a pull request, I will be very much appreciated.

**Comment by jslim89** [comment]
@renfeisong I have merged #12 pull request, you may try again

**Comment by renfeisong** [comment]
@jslim89 After applying the patch it seems that the problem is gone for now. Thanks a lot!

**Comment by jslim89** [comment]
You're most welcome.
