### ISSUE TITLE
Swift not works when include RSA-objc

### ISSUE THREAD

**Issue by williamhqs** [jslim89/RSA-objc#5]
This works good on Objective-C, but when i import RSA-objc swift, it has many errors:
![screen shot 2015-06-25 at 10 53 37 am](https://cloud.githubusercontent.com/assets/354829/8345954/8d5eaddc-1b28-11e5-96d4-6848e413c523.png)

**Comment by jslim89** [comment]
I created a sample project in swift, refer to #9
