### ISSUE TITLE
publicEncrypt  return nil

### ISSUE THREAD

**Issue by ludy520** [jslim89/RSA-objc#6]
NSString *password=@"123456";

[JSRSA sharedInstance].publicKey=@"public_key.pem";
[JSRSA sharedInstance].privateKey=@"private_key.pem";

 NSString *upass=[[JSRSA sharedInstance] publicEncrypt:password];

hi,when i use this util ,sometimes encrypt text return nil

**Comment by jslim89** [comment]
Refer to this issue https://github.com/jslim89/RSA-objc/issues/3
I'm quite busy these day, perhaps you can fix it and submit a pull request.
Thanks
