### ISSUE TITLE
Encrypt and Decrypt text with custom Private and Public keys.

### ISSUE THREAD

**Issue by WarisSaqi** [jslim89/RSA-objc#7]
Hi all,
I am working on a project in which i need to encrypt and decrypt the data using private and public keys but these both keys are came from server but in example it take keys from pem files, if there is any way to encrypt the data using own Private and Public keys kindly guide me. 
Thanks in advance.

**Comment by jslim89** [comment]
Hi @WarisSaqi,
one of the way is to download the key to the the device first _(download during runtime I mean)_, then only load to `JSRSA` object. If not, you need to modify the script. We will appreciate if you submit a pull request for this feature _(if you did it)_. Thanks
