### ISSUE TITLE
Not able to encrypt some strings in device

### ISSUE THREAD

**Issue by SwathiBhatK** [jslim89/RSA-objc#8]
For some string when i am running in iPhone, i get encrypted string as follows

 PWzAkKHRhbitHz7L0fn4teVED6xbd8xUmJpwi8qC+eJPGI0JYJD2zCbz+vHj3pF8jSS24Avw0BnlPF65QUtuzzUy7gw1FO2ICoSUTfiZ13Dy6lavVZJE7kiw7eByyxRhesYpFZIHSgn+CMObns9wyi5G5LovhJyf+XDCnvd1g1ChkRcKRVPspPm7Bc3R2B+Gkz/S2QVvSgUwphuyl5lRGQtgvkxItOY2QrNmjbSudoeTfH5TnNl+gq8cqygr6tSQnRUJiZF+/MC3+H0PBldtmkVgdB2fnlp083UCfUbmJgRnE84pUq9IpHmD2C3BxP1KNnNTA86xVB/m4WFEx7WoBph1KkYtjsTaLtFLIrX6P1HfC23n9YHWxELRewTFUsh9PxphN8BtFO4q0VaQRLw4zvLJlTKS8GP+37BsX4ZSgf1h1S3E8u5AlVfJPEbUgukyCn4K3MEvGqQ9R236ptBO1rO/sM5tqB4DYE86oQbNWqx4zTcYdS8j2kKCLX4gyUzrFIO03GNARpYuJKHJbDrK0PiREuPM/a024M9WbbnTnJZdwrBWeGaWajUyY8aUPdpcsz6VOjjWNxpb8GfMRxPr8hrLnayrGSYNWrEpLJHY6fZMBS+FVq2KSJJoPlDDtdkMK+I++JYqnMIH3apMuy543yreadwiYz5WFuzK+D2BUq40UBhOA6mYtShFQRwRS48O7rh2jaPNmjSj8SnlNmpcnucomWsUTtqslMfrKeOCYsBh5VShxWQwEWICWF9FQ8EDGbpWYJz9q/6yWe5+7IWrnMkKKRa3JVAszrE+R3MzIamoomw3Yns7OabGECMfKkODcvht3Sr195RUIKsvnk06qQJZc93pcTBLWk5otA7BN03rUwcTZfmCjy3Q98PPjWwL3Y2Vlu+pyJ/4+EROnGVNPYBnESO73lLShAc3kA+VCmvapilSbAIlAGdjlJHnpwR+GMIOPkpAKhUDjJhUOTEH+ijSNFNuyyYb/gp+hrJU3JOm08fTBIQdNvWITWmX/rQPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

This is creating issues while decrypting last chunk. It is throwing bad access.

**Comment by jslim89** [comment]
Can you test with php script? To find out whether is encryption or decryption problem

**Comment by jslim89** [comment]
Refer to #12
