### ISSUE TITLE
Swift Compilation Issue

### ISSUE THREAD

**Issue by qbalsdon** [jslim89/RSA-objc#9]
When completing the import, I cannot compile the project. I get:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSRSA", referenced from:
      type metadata accessor for ObjectiveC.JSRSA in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jslim89** [comment]
@qbalsdon Can you provide screenshots?

**Comment by jslim89** [comment]
I've created a [sample project](https://dl.dropboxusercontent.com/u/30636914/temp/RSASwift.zip), you can check with it, see anything missing

**Comment by qbalsdon** [comment]
Great thanks! I am encrypting and decrypting! You are a lifesaver!

**Comment by jslim89** [comment]
Glad I'm helping you
